// priority: 0

console.info('Hello, World! (You will only see this line once in console, during startup)')

events.listen('item.registry', event => {
  // Register new items here
  // event.create('example_item').displayName('Example Item')
})

events.listen('block.registry', event => {
  // Register new blocks here
  // event.create('example_block').material('wood').hardness(1.0).displayName('Example Block')
})

events.listen('rei.hide.items', function (event) {
  event.hide('minecraft:repeating_command_block')
  event.hide('minecraft:chain_command_block')
  event.hide('minecraft:bat_spawn_egg')
  event.hide('minecraft:bee_spawn_egg')
  event.hide('minecraft:blaze_spawn_egg')
  event.hide('minecraft:cat_spawn_egg')
  event.hide('minecraft:cave_spider_spawn_egg')
  event.hide('minecraft:chicken_spawn_egg')
  event.hide('minecraft:cod_spawn_egg')
  event.hide('minecraft:cow_spawn_egg')
  event.hide('minecraft:creeper_spawn_egg')
  event.hide('minecraft:dolphin_spawn_egg')
  event.hide('minecraft:donkey_spawn_egg')
  event.hide('minecraft:drowned_spawn_egg')
  event.hide('minecraft:elder_guardian_spawn_egg')
  event.hide('minecraft:enderman_spawn_egg')
  event.hide('minecraft:endermite_spawn_egg')
  event.hide('minecraft:evoker_spawn_egg')
  event.hide('minecraft:fox_spawn_egg')
  event.hide('minecraft:ghast_spawn_egg')
  event.hide('minecraft:guardian_spawn_egg')
  event.hide('minecraft:hoglin_spawn_egg')
  event.hide('minecraft:horse_spawn_egg')
  event.hide('minecraft:husk_spawn_egg')
  event.hide('minecraft:llama_spawn_egg')
  event.hide('minecraft:magma_cube_spawn_egg')
  event.hide('minecraft:mooshroom_spawn_egg')
  event.hide('minecraft:mule_spawn_egg')
  event.hide('minecraft:ocelot_spawn_egg')
  event.hide('minecraft:panda_spawn_egg')
  event.hide('minecraft:parrot_spawn_egg')
  event.hide('minecraft:phantom_spawn_egg')
  event.hide('minecraft:pig_spawn_egg')
  event.hide('minecraft:piglin_spawn_egg')
  event.hide('minecraft:piglin_brute_spawn_egg')
  event.hide('minecraft:pillager_spawn_egg')
  event.hide('minecraft:polar_bear_spawn_egg')
  event.hide('minecraft:pufferfish_spawn_egg')
  event.hide('minecraft:rabbit_spawn_egg')
  event.hide('minecraft:ravager_spawn_egg')
  event.hide('minecraft:salmon_spawn_egg')
  event.hide('minecraft:sheep_spawn_egg')
  event.hide('minecraft:shulker_spawn_egg')
  event.hide('minecraft:silverfish_spawn_egg')
  event.hide('minecraft:skeleton_spawn_egg')
  event.hide('minecraft:skeleton_horse_spawn_egg')
  event.hide('minecraft:slime_spawn_egg')
  event.hide('minecraft:spider_spawn_egg')
  event.hide('minecraft:squid_spawn_egg')
  event.hide('minecraft:stray_spawn_egg')
  event.hide('minecraft:strider_spawn_egg')
  event.hide('minecraft:trader_llama_spawn_egg')
  event.hide('minecraft:tropical_fish_spawn_egg')
  event.hide('minecraft:turtle_spawn_egg')
  event.hide('minecraft:vex_spawn_egg')
  event.hide('minecraft:villager_spawn_egg')
  event.hide('minecraft:vindicator_spawn_egg')
  event.hide('minecraft:wandering_trader_spawn_egg')
  event.hide('minecraft:witch_spawn_egg')
  event.hide('minecraft:wither_skeleton_spawn_egg')
  event.hide('minecraft:wolf_spawn_egg')
  event.hide('minecraft:zoglin_spawn_egg')
  event.hide('minecraft:zombie_spawn_egg')
  event.hide('minecraft:zombie_horse_spawn_egg')
  event.hide('minecraft:zombie_villager_spawn_egg')
  event.hide('minecraft:zombified_piglin_spawn_egg')
  event.hide('the_bumblezone:honey_slime_spawn_egg')
  event.hide('campanion:rope_bridge_post')
  event.hide('campanion:grappling_hook')
  event.hide('campanion:skipping_stone')
  event.hide('ironchest:silver_chest')
  event.hide('ironchest:copper_chest')
  event.hide('ironchest:wood_copper_upgrade')
  event.hide('ironchest:copper_silver_upgrade')
  event.hide('ironchest:copper_iron_upgrade')
  event.hide('ironchest:silver_gold_upgrade')
  event.hide('byg:byg_logo')
  event.hide('curios:amulet')
  event.hide('curios:crown')
  event.hide('curios:ring')
  event.hide('curios:knuckles')
})