# RandomPatches configuration

# Options related to the movement speed limits.
[speedLimits]
	# The maximum player elytra speed.
	# The vanilla default is 300.0.
	# Min: 1.0
	# Max: 3.4028234663852886E38
	# Default: 1000000.0
	maxPlayerElytraSpeed = 1000000.0
	# The maximum player vehicle speed.
	# The vanilla default is 100.0.
	# Min: 1.0
	# Max: 1.7976931348623157E308
	# Default: 1000000.0
	maxPlayerVehicleSpeed = 1000000.0
	# The maximum player speed.
	# The vanilla default is 100.0.
	# Min: 1.0
	# Max: 3.4028234663852886E38
	# Default: 1000000.0
	maxPlayerSpeed = 1000000.0

# Options related to the disconnect timeouts.
[timeouts]
	# The interval at which the server sends the KeepAlive packet.
	# Min: 1
	# Max: 2147483647
	# Default: 15
	keepAlivePacketInterval = 15
	# The read timeout in seconds.
	# This is the time it takes for a player to be disconnected after not responding to a KeepAlive packet.
	# This value is automatically rounded up to a product of 15.
	# Min: 1
	# Max: 2147483647
	# Default: 90
	readTimeout = 90
	# The login timeout in ticks.
	# Min: 1
	# Max: 2147483647
	# Default: 900
	loginTimeout = 900

# Options that don't fit into any other categories.
[misc]
	# Enables the /rpreload command.
	# Default: true
	rpreload = true

